---
#переменные
- name: set nginx_stub_exporter variables
  set_fact:
    nginx_stub_exporter_port: 9113
    nginx_stub_exporter_user: nginx_stub_exporter
  tags: ['nginx_exporter', 'stub_status']


#юзер
- name: create nginx_stub_exporter usr
  user:
    name: "{{ nginx_stub_exporter_user }}"
    shell: /usr/sbin/nologin
    createhome: no
    state: present
  become: yes
  tags: ['nginx_exporter', 'stub_status']


#загрузить экспортер прометеуса
- name: download nginx-prometheus-exporter
  get_url:
    url: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.1.0/nginx-prometheus-exporter_1.1.0_linux_amd64.tar.gz"
    dest: "/tmp/nginx-prometheus-exporter.tar.gz"
    mode: '0644'
  tags: ['nginx_exporter', 'stub_status']
#рспаковать
- name: extract nginx-prometheus-exporter
  unarchive:
    src: "/tmp/nginx-prometheus-exporter.tar.gz"
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'
  become: yes
  tags: ['nginx_exporter', 'stub_status']


#создать systemd сервис
- name: create systemd-servce for nginx-promtheus-exporter
  copy:
    content: |
      [Unit]
      Description=Nginx Prometheus Exporter (stub_status)
      After=network.target nginx.service

      [Service]
      Type=simple
      User={{ nginx_stub_exporter_user }}
      ExecStart=/usr/local/bin/nginx-prometheus-exporter -nginx.scrape-uri=http://localhost/stub_status
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/nginx-prometheus-exporter.service
    mode: '0644'
    owner: root
    group: root
  become: yes
  tags: ['nginx_exporter', 'stub_status']


#start & enable service
- name: enable & start nginx-prometheus-exporter
  systemd:
    name: nginx-prometheus-exporter
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes
  tags: ['nginx_exporter', 'stub_status']


#жду подъём сервиса
- name: wait service to be ready
  wait_for:
    host: localhost
    port: "{{ nginx_stub_exporter_port }}"
    delay: 2
    timeout: 30
  tags: ['nginx_exporter', 'stub_status']


#чекаю метрики
- name: check metrics
  shell: "curl -s http://localhost:{{ nginx_stub_exporter_port }}/metrics | grep -q nginx_requests && echo 'OK' || echo 'FAILED'"
  register: stub_metrics
  changed_when: false
  tags: ['nginx_exporter', 'stub_status']